python: do not fail displaying a non-C error (fixes #3866)
The binding does a raise Error('failed to create object') but the local Error
exception class expects a lasso error code, and will thus fail if printed.

  File ".../lasso.py", line 54, in __str__
    return '<lasso.%s(%s): %s>' % (self.__class__.__name__, self.code,
             _lasso.strError(self.code))
  TypeError: an integer is required